# -*- coding: utf-8 -*-
"""code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EFUhCCs4WmnY8PBJ2yHHsgt0HmCiOsk0
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/heart.csv")

#Basic Inspection
print("Shape:", df.shape)
print("\nData Types: ")
print( df.dtypes)
print("\nMissing Values: ")
print(df.isnull().sum())
print("\nSummary Statistics: ")
print(df.describe().round(2))

#Target Distribution
print("\nTarget Distribution: ")
print(df["target"].value_counts())
print(df["target"].value_counts(normalize=True).mul(100).round(1))
print("  ")
#correlation with target
corr = df.corr()["target"].sort_values(ascending=False)
print("Correlation with Target:")
print(corr.round(3))

#EDA Charts
fig, axes = plt.subplots(2, 3, figsize=(14,8))

df["age"].hist(ax=axes[0,0], bins=20, color='steelblue')
axes[0,0].set_title("Age Distribution")

df["thalach"].hist(ax=axes[0,1], bins=20, color="purple")
axes[0,1].set_title("Max Heart Rate")

df.groupby("target")["age"].mean().plot(kind="bar", ax=axes[0,2], color=["#E74C3C","#2ECC71"])
axes[0,2].set_title("Mean Age by Target")

df.groupby("sex")["target"].mean().plot(kind="bar", ax=axes[1, 0])
axes[1,0].set_title("Disease Rate by Sex")

df.groupby("cp")["target"].mean().plot(kind="bar", ax=axes[1,1])
axes[1,1].set_title("Disease Rate by Chest Pain Type")

sns.heatmap(df.corr(), ax=axes[1,2], cmap="coolwarm", annot=False)
axes[1,2].set_title("Correlation Heatmap")

plt.tight_layout()
plt.savefig("eda_overview.png", dpi=150)
plt.show()

# 1.The dataset appears reasonably balanced. The class split is approximately 55% disease present
# and 45% no disease.

# 2.The three features most strongly correlated with heart disease appear to be:
# - cp (chest pain type) → strong positive correlation
# - thalach (maximum heart rate) → positive correlation
# - oldpeak → strong negative correlation

# 3.No obvious missing values appear in the dataset after inspection.
# The dataset seems clean and ready for modelling.

# 4. Chest pain type clearly varies by disease presence. Patients with cp values 1, 2, and 3
# show much higher disease rates than patients with cp value 0.

# 5. Age distribution does not appear drastically different between patients with and without disease.
# Mean ages are fairly close, suggesting age alone may not be a strong predictor.

# 6.There may be some outliers in trestbps and chol because medical measurements can
# contain unusually high values.
# Histograms, box plots, or extreme ranges in summary statistics help identify these outliers.

# Data Cleaning

import pandas as pd
import numpy as np

df = pd.read_csv("/content/heart.csv")
print("\nMissing Values Before Cleaning:")
print(df.isnull().sum())
print("  ")

print(f"Original shape: {df.shape}")
print("  ")

# Check for duplicates
print(f"Duplicates: {df.duplicated().sum()}")
df = df.drop_duplicates()
print("  ")

# Handle missing values
# Some versions use "?" for missing — replace with NaN:
df = df.replace("?", np.nan)

# Convert columns to numeric (in case "?" left them as object):
for col in df.columns:
    df[col] = pd.to_numeric(df[col], errors="coerce")

print("Missing after conversion:")
print(df.isnull().sum())
print("  ")

# ── Handle impossible 0 values ──
# Cholesterol of 0 is physiologically impossible:
print(f"Zero cholesterol: {(df['chol'] == 0).sum()}")
df["chol"] = df["chol"].replace(0, np.nan)
print("  ")

# Resting BP of 0 is also impossible:
print(f"Zero trestbps: {(df['trestbps'] == 0).sum()}")
df["trestbps"] = df["trestbps"].replace(0, np.nan)
print("  ")

# ── Fill remaining NaN with median ──
numeric_cols = df.select_dtypes(include="number").columns
df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].median())

#Checking ca column
print("\nValue Counts for ca:")
print(df["ca"].value_counts())

# Replace invalid value 4 with NaN
df["ca"] = df["ca"].replace(4, np.nan)

# Fill missing values with median
df["ca"] = df["ca"].fillna(df["ca"].median())

# checking thal column
print("\nValue Counts for thal:")
print(df["thal"].value_counts())

# Replace invalid value 4 with NaN
df["thal"] = df["thal"].replace(4, np.nan)

# Fill missing values with median
df["thal"] = df["thal"].fillna(df["thal"].median())


# =========================================
# OUTLIER CHECK — chol
# =========================================

Q1 = df["chol"].quantile(0.25)
Q3 = df["chol"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

# Find outliers
chol_outliers = df[
    (df["chol"] < lower) |
    (df["chol"] > upper)
]

print("\nChol Outliers Found:")
print(len(chol_outliers))

print(f"Lower Bound: {lower:.2f}")
print(f"Upper Bound: {upper:.2f}")

# CAP OUTLIERS — chol

df["chol"] = df["chol"].clip(
    lower=lower,
    upper=upper
)

# CAP OUTLIERS — trestbps

Q1_bp = df["trestbps"].quantile(0.25)
Q3_bp = df["trestbps"].quantile(0.75)

IQR_bp = Q3_bp - Q1_bp

lower_bp = Q1_bp - 1.5 * IQR_bp
upper_bp = Q3_bp + 1.5 * IQR_bp

df["trestbps"] = df["trestbps"].clip(
    lower=lower_bp,
    upper=upper_bp
)
print("  ")
print("Missing after cleaning:")
print(df.isnull().sum())
print("  ")

print("\nTotal Missing Values:")
print(df.isnull().sum().sum())
print("  ")

print(f"Final shape: {df.shape}")

df.to_csv("heart_clean.csv", index=False)
print("\nSaved cleaned dataset as heart_clean.csv")

import pandas as pd
import numpy as np

df = pd.read_csv("/content/heart_clean.csv")

# ── New features based on domain knowledge ──

# Age categories:
df["age_group"] = pd.cut(df["age"],
                          bins=[0, 40, 55, 70, 120],
                          labels=["young","middle","senior","elderly"])

# High cholesterol flag (>240 mg/dl is considered high):
df["high_chol"] = (df["chol"] > 240).astype(int)

# High blood pressure flag (>140 mm Hg):
df["high_bp"] = (df["trestbps"] > 140).astype(int)

# Low max heart rate relative to age (thalach < 220 - age is the expected max):
df["expected_hr"] = 220 - df["age"]
df["hr_ratio"]    = df["thalach"] / df["expected_hr"]

# Significant ST depression flag:
df["sig_oldpeak"] = (df["oldpeak"] > 2.0).astype(int)

# Encode age_group:
df = pd.get_dummies(df, columns=["age_group"], drop_first=True)

# Drop expected_hr (intermediate calculation):
df.drop(columns=["expected_hr"], inplace=True)

print(df.columns.tolist())
print(df.shape)

# CORRELATION OF NEW FEATURES
new_features = [
    "high_chol",
    "high_bp",
    "hr_ratio",
    "sig_oldpeak"
]

print("\nCORRELATION WITH TARGET:\n")

print(
    df[new_features + ["target"]]
    .corr()["target"]
)

# SAVE FINAL DATASET
df.to_csv("heart_engineered.csv", index=False)
print("\nSaved as heart_engineered.csv")

# hr_ratio and sig_oldpeak often show stronger correlations
# with heart disease than high_chol or high_bp.

# hr_ratio may provide additional information because it
# normalizes heart rate relative to patient age.

# Some engineered features may be dropped later if they
# show weak correlation or create multicollinearity.

import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split

df = pd.read_csv("/content/heart_engineered.csv")

X = df.drop(columns=["target"])
y = df["target"]

# Identify column types:
numeric_features  = X.select_dtypes(include=["number"]).columns.tolist()
cat_features       = X.select_dtypes(include=["object","bool"]).columns.tolist()
print("Numeric:", numeric_features)
print("Categorical:", cat_features)

# Split first — before any fitting:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y)

# Define transformers:
numeric_transformer = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler",  StandardScaler())
])

# ColumnTransformer — applies different steps to different columns:
preprocessor = ColumnTransformer([
    ("num", numeric_transformer, numeric_features),
],  remainder="passthrough")   # keep any remaining columns as-is

# Full pipeline with a placeholder model:
from sklearn.linear_model import LogisticRegression
full_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model",        LogisticRegression(random_state=42, max_iter=1000))
])

full_pipeline.fit(X_train, y_train)
print(f"Baseline accuracy: {full_pipeline.score(X_test, y_test):.2%}")

# Inspect preprocessor
preprocessor = full_pipeline.named_steps['preprocessor']

# Access scaler inside numeric transformer
scaler = preprocessor.named_transformers_['num'].named_steps['scaler']

# Print scaler means
print('Scaler means (first 5):')
print(scaler.mean_[:5])

# Print number of processed features
print('Number of features processed:')
print(scaler.n_features_in_)

# PRINT TRAIN / TEST SHAPES

print("\nX_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

print("\ny_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

# PRINT CLASS DISTRIBUTION

print("\ny_train value counts:")
print(y_train.value_counts())

print("\ny_test value counts:")
print(y_test.value_counts())

# PRINT CLASS RATIOS
print("\ny_train ratios:")
print(y_train.value_counts(normalize=True))

print("\ny_test ratios:")
print(y_test.value_counts(normalize=True))

# stratify=y keeps class proportions similar
# in both train and test datasets.

# ColumnTransformer allows different preprocessing
# steps for different column types in one pipeline.

# A normal Pipeline applies the same transformations
# to all columns, but ColumnTransformer can handle
# numeric and categorical features separately.

import pandas as pd
import numpy as np
from sklearn.linear_model    import LogisticRegression
from sklearn.tree            import DecisionTreeClassifier
from sklearn.ensemble        import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neighbors       import KNeighborsClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.metrics         import f1_score, roc_auc_score

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

models = {
    "Logistic Regression":      LogisticRegression(random_state=42, max_iter=1000),
    "Decision Tree":            DecisionTreeClassifier(random_state=42),
    "Random Forest":            RandomForestClassifier(random_state=42),
    "Gradient Boosting":        GradientBoostingClassifier(random_state=42),
    "KNN":                      KNeighborsClassifier()
}

results = []
for name, model in models.items():
    pipe = Pipeline([("preprocessor", preprocessor), ("model", model)])
    f1   = cross_val_score(pipe, X_train, y_train, cv=cv, scoring="f1")
    auc  = cross_val_score(pipe, X_train, y_train, cv=cv, scoring="roc_auc")
    acc  = cross_val_score(pipe, X_train, y_train, cv=cv, scoring="accuracy")
    results.append({
        "Model":    name,
        "CV F1":    f1.mean(),
        "CV AUC":   auc.mean(),
        "CV Acc":   acc.mean(),
        "F1 Std":   f1.std()
    })
    print(f"{name}: F1={f1.mean():.3f} ± {f1.std():.3f}  AUC={auc.mean():.3f}")
    results_df = pd.DataFrame(results).sort_values("CV F1", ascending=False)
print("\n", results_df.round(3))

plt.figure(figsize=(10, 5))

# Create bar chart
plt.barh(
    results_df["Model"],
    results_df["CV F1"],
    xerr=results_df["F1 Std"]
)

# Labels and title
plt.xlabel("Cross-Validation F1 Score")
plt.ylabel("Model")
plt.title("Model Comparison — CV F1 Scores")

# Grid
plt.grid(axis="x", linestyle="--", alpha=0.5)

# Save chart
plt.tight_layout()
plt.savefig("chart_model_comparison.png", dpi=150)

# Show chart
plt.show()

# Logistic Regression appears to have the best CV F1 score
# because its bar is slightly higher than the other models.

# Decision Tree appears to be the most consistent model
# because it has the smallest error bar (lowest std).

# Logistic Regression would be a strong candidate for tuning
# because it achieved the best overall F1 performance while
# remaining relatively stable across folds.

# KNN appears slightly less consistent because its error bars
# are wider, suggesting higher variation across folds.

# None of the models performed extremely poorly.
# All models achieved relatively similar F1 scores,
# which suggests the dataset is fairly learnable.

# Selected model for tuning:
# Logistic Regression

from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

# tuning Random Forest (adjust for your best model):
best_model_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model",        RandomForestClassifier(random_state=42))
])

param_dist = {
    "model__n_estimators":     randint(100, 500),
    "model__max_depth":        [4, 6, 8, 10, None],
    "model__min_samples_leaf": randint(1, 10),
    "model__class_weight":     [None, "balanced"]
}

rand_search = RandomizedSearchCV(
    best_model_pipeline,
    param_dist,
    n_iter=30,
    cv=5,
    scoring="roc_auc",    # optimise for AUC — threshold-independent
    n_jobs=-1,
    random_state=42,
    verbose=1
)

rand_search.fit(X_train, y_train)

print(f"Best params: {rand_search.best_params_}")
print(f"Best CV AUC: {rand_search.best_score_:.3f}")

from sklearn.metrics import roc_auc_score

# Clean parameter names
best_params_cleaned = {
    key.replace("model__", ""): value
    for key, value in rand_search.best_params_.items()
}

# Create tuned pipeline
tuned_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", RandomForestClassifier(
        random_state=42,
        **best_params_cleaned
    ))
])

# Train tuned model
tuned_pipeline.fit(X_train, y_train)

# Predict probabilities
train_probs = tuned_pipeline.predict_proba(X_train)[:, 1]
test_probs = tuned_pipeline.predict_proba(X_test)[:, 1]

# Calculate AUC
train_auc = roc_auc_score(y_train, train_probs)
test_auc = roc_auc_score(y_test, test_probs)

# Print AUC scores
print(f"Train AUC: {train_auc:.3f}")
print(f"Test AUC:  {test_auc:.3f}")

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import RandomizedSearchCV
from sklearn.pipeline import Pipeline
from sklearn.metrics import roc_auc_score
from scipy.stats import uniform

# LOGISTIC REGRESSION PIPELINE

best_model_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LogisticRegression(
        random_state=42,
        max_iter=1000
    ))
])

# PARAMETER SEARCH SPACE

param_dist = {
    "model__C": uniform(0.01, 10),
    "model__penalty": ["l2"],
    "model__solver": ["lbfgs", "liblinear"],
    "model__class_weight": [None, "balanced"]
}


# RANDOMIZED SEARCH
rand_search = RandomizedSearchCV(
    estimator=best_model_pipeline,
    param_distributions=param_dist,
    n_iter=30,
    cv=5,
    scoring="roc_auc",
    n_jobs=-1,
    random_state=42,
    verbose=1
)

# Train search
rand_search.fit(X_train, y_train)

# Print best results
print("Best Parameters:")
print(rand_search.best_params_)

print(f"\nBest CV AUC: {rand_search.best_score_:.3f}")


# CLEAN PARAMETERS
best_params_cleaned = {
    key.replace("model__", ""): value
    for key, value in rand_search.best_params_.items()
}

# FINAL TUNED PIPELINE

tuned_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LogisticRegression(
        random_state=42,
        max_iter=1000,
        **best_params_cleaned
    ))
])

# Train tuned model
tuned_pipeline.fit(X_train, y_train)

# Predict probabilities
train_probs = tuned_pipeline.predict_proba(X_train)[:, 1]
test_probs = tuned_pipeline.predict_proba(X_test)[:, 1]

# Calculate AUC
train_auc = roc_auc_score(y_train, train_probs)
test_auc = roc_auc_score(y_test, test_probs)

# Print AUC scores
print(f"\nTrain AUC: {train_auc:.3f}")
print(f"Test AUC:  {test_auc:.3f}")


# Smaller train-test AUC gap means better generalization
# and less overfitting than Random Forest.

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import (confusion_matrix, classification_report,
                             roc_curve, roc_auc_score,
                             precision_recall_curve, average_precision_score)

y_pred      = tuned_pipeline.predict(X_test)
y_proba     = tuned_pipeline.predict_proba(X_test)[:, 1]

# ── Classification Report ──
print(classification_report(y_test, y_pred,
      target_names=["No Disease", "Heart Disease"]))

# ── Confusion Matrix ──
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(7, 5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["No Disease","Heart Disease"],
            yticklabels=["No Disease","Heart Disease"])
plt.title("Confusion Matrix — Tuned Model", fontsize=14)
plt.tight_layout()
plt.savefig("chart_confusion_final.png", dpi=150)

# ── ROC Curve ──
fpr, tpr, _ = roc_curve(y_test, y_proba)
auc = roc_auc_score(y_test, y_proba)
plt.figure(figsize=(7, 6))
plt.plot(fpr, tpr, label=f"AUC = {auc:.3f}", color="#1E3A5F", lw=2)
plt.fill_between(fpr, tpr, alpha=0.1, color="#1E3A5F")
plt.plot([0,1],[0,1],"k--", label="Random baseline")
plt.xlabel("False Positive Rate (1 - Specificity)")
plt.ylabel("True Positive Rate (Sensitivity)")
plt.title("ROC Curve — Heart Disease Classifier")
plt.legend()
plt.tight_layout()
plt.savefig("chart_roc_final.png", dpi=150)
plt.show()

# ── Sensitivity (Recall) for class 1 ──
tn, fp, fn, tp = cm.ravel()
sensitivity = tp / (tp + fn)
specificity = tn / (tn + fp)
print(f"Sensitivity (Recall): {sensitivity:.2%}")
print(f"Specificity:          {specificity:.2%}")
print(f"AUC:                  {auc:.3f}")

# PRECISION-RECALL CURVE

precision, recall, thresholds = precision_recall_curve(
    y_test,
    y_proba
)

ap = average_precision_score(
    y_test,
    y_proba
)

# Create PR curve
plt.figure(figsize=(7, 6))

plt.plot(
    recall,
    precision,
    label=f"AP = {ap:.3f}"
)

# Labels and title
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.title("Precision-Recall Curve")

# Legend
plt.legend()

# Save chart
plt.tight_layout()
plt.savefig("chart_pr_curve.png", dpi=150)

# Show chart
plt.show()

# Print AP score
print(f"Average Precision: {ap:.3f}")

# FALSE NEGATIVES

print(f"False Negatives (missed disease cases): {fn}")

# False negatives are patients who actually
# had heart disease but the model predicted
# no disease.

# THRESHOLD FOR 90% SENSITIVITY

# ROC curve values
fpr, tpr, roc_thresholds = roc_curve(
    y_test,
    y_proba
)

# Find threshold closest to 0.90 sensitivity
target_sensitivity = 0.90

idx = np.argmax(tpr >= target_sensitivity)

best_threshold = roc_thresholds[idx]

print(f"Threshold for ~90% sensitivity: {best_threshold:.3f}")
print(f"Achieved Sensitivity: {tpr[idx]:.3f}")

# Sensitivity (Recall): 78.79%

# The model achieved an AUC above 0.85, which indicates strong classification performance.
# An AUC near 0.90 suggests the model separates disease and non-disease patients effectively.
# However, clinical use usually requires additional validation, testing, and safety
# review before deployment.

# Lowering the classification threshold would increase sensitivity and allow the model to catch more
# heart disease cases.
# Increasing sensitivity is important in healthcare because missing real disease cases is more dangerous
# than creating some extra false positives.
# Threshold for ~90% sensitivity: 0.233

import joblib, json
from datetime import datetime
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score

# ── Save the trained pipeline ──
joblib.dump(tuned_pipeline, "heart_model.pkl")
print("Model saved: heart_model.pkl")

# ── Save metadata ──
metadata = {
    "project":        "Heart Disease Classifier",
    "model_type":     type(tuned_pipeline.named_steps["model"]).__name__,
    "features":       X.columns.tolist(),
    "target":         "target",
    "trained_on":     datetime.now().isoformat(),
    "train_samples":  int(X_train.shape[0]),
    "test_samples":   int(X_test.shape[0]),
    "metrics": {
        "test_accuracy": round(accuracy_score(y_test, y_pred), 4),
        "test_f1":       round(f1_score(y_test, y_pred), 4),
        "test_auc":      round(roc_auc_score(y_test, y_proba), 4),
        "sensitivity":   round(float(sensitivity), 4),
        "specificity":   round(float(specificity), 4)
    },
    "best_params":    {k: str(v) for k, v in rand_search.best_params_.items()}
}

with open("heart_model_metadata.json", "w") as f:
    json.dump(metadata, f, indent=2)
print("Metadata saved: heart_model_metadata.json")

# ── Verify: load and predict ──
loaded = joblib.load("heart_model.pkl")
verify = loaded.predict(X_test)
import numpy as np
print(f"Load verified: {np.array_equal(y_pred, verify)}")

with open("heart_model_metadata.json") as f:

    print(
        json.dumps(
            json.load(f),
            indent=2
        )
    )

# SAVE FEATURE LIST
with open("heart_features.json", "w") as f:

    json.dump(
        X.columns.tolist(),
        f,
        indent=2
    )

print("Saved: heart_features.json")

# SAVE FINAL DATASET
df.to_csv(
    "heart_final.csv",
    index=False
)
print("Saved: heart_final.csv")

import os

files = [
    "heart_model.pkl",
    "heart_model_metadata.json",
    "heart_features.json",
    "heart_final.csv"
]

print("FILE CHECK:\n")

for file in files:

    print(
        f"{file}:",
        os.path.exists(file)
    )

import joblib, json, logging
from datetime import datetime
import pandas as pd

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("HeartPredictor")

class HeartDiseasePredictor:
    """Production heart disease risk predictor."""

    VALID_RANGES = {
        "age":      (18, 120),
        "trestbps": (60, 250),
        "chol":     (50, 600),
        "thalach":  (50, 250),
        "oldpeak":  (0, 10)
    }

    def __init__(self, model_path, metadata_path):
        self.model    = joblib.load(model_path)
        with open(metadata_path) as f:
            self.meta = json.load(f)
        self.features = self.meta["features"]
        logger.info(f"Loaded. Test AUC: {self.meta['metrics']['test_auc']}")

    def _validate(self, patient):
        for field, (lo, hi) in self.VALID_RANGES.items():
            if field in patient:
                val = patient[field]
                if not (lo <= val <= hi):
                    raise ValueError(f"{field}={val} out of range [{lo},{hi}]")

    def predict(self, patient_dict):
        try:
            self._validate(patient_dict)
            df    = pd.DataFrame([patient_dict])[self.features]
            pred  = self.model.predict(df)[0]
            proba = self.model.predict_proba(df)[0][1]
            risk  = "High" if proba > 0.7 else "Moderate" if proba > 0.4 else "Low"
            result = {
                "prediction":  int(pred),
               "label": "Heart Disease Detected" if pred == 1 else "No Disease",
                "probability": round(float(proba), 4),
                "risk_level":  risk,
                "timestamp":   datetime.now().isoformat()
            }
            logger.info(f"Prediction: {result['label']} (p={proba:.2%}, risk={risk})")
            return result
        except Exception as e:
            logger.error(f"Error: {e}")
            return {"error": str(e)}

    def batch_predict(self, patients):
      results = []
      for patient in patients:
          result = self.predict(patient)
          results.append(result)
      return results

# Create predictor instance
predictor = HeartDiseasePredictor(
    "heart_model.pkl",
    "heart_model_metadata.json"
)

patients = [

    # Patient 1 — high risk
    {
        "age": 62,
        "sex": 1,
        "cp": 0,
        "trestbps": 150,
        "chol": 270,
        "fbs": 1,
        "restecg": 0,
        "thalach": 105,
        "exang": 1,
        "oldpeak": 3.5,
        "slope": 0,
        "ca": 3,
        "thal": 2
    },

    # Patient 2 — low risk
    {
        "age": 32,
        "sex": 0,
        "cp": 2,
        "trestbps": 115,
        "chol": 190,
        "fbs": 0,
        "restecg": 0,
        "thalach": 178,
        "exang": 0,
        "oldpeak": 0.0,
        "slope": 2,
        "ca": 0,
        "thal": 3
    },

    # Patient 3 — borderline
    {
        "age": 51,
        "sex": 1,
        "cp": 1,
        "trestbps": 130,
        "chol": 245,
        "fbs": 0,
        "restecg": 1,
        "thalach": 145,
        "exang": 0,
        "oldpeak": 1.2,
        "slope": 1,
        "ca": 1,
        "thal": 3
    },

    # Patient 4 — elderly male
    {
        "age": 68,
        "sex": 1,
        "cp": 0,
        "trestbps": 160,
        "chol": 300,
        "fbs": 1,
        "restecg": 2,
        "thalach": 99,
        "exang": 1,
        "oldpeak": 2.8,
        "slope": 0,
        "ca": 2,
        "thal": 2
    },

    # Patient 5 — young female
    {
        "age": 28,
        "sex": 0,
        "cp": 3,
        "trestbps": 108,
        "chol": 168,
        "fbs": 0,
        "restecg": 0,
        "thalach": 185,
        "exang": 0,
        "oldpeak": 0.0,
        "slope": 2,
        "ca": 0,
        "thal": 3
    }
]

# PREPROCESS PATIENTS
processed_patients = []

for patient in patients:

    p = patient.copy()

    # High cholesterol
    p["high_chol"] = int(
        p["chol"] > 240
    )

    # High blood pressure
    p["high_bp"] = int(
        p["trestbps"] > 140
    )

    # Heart rate ratio
    expected_hr = 220 - p["age"]

    p["hr_ratio"] = (
        p["thalach"] / expected_hr
    )

    # Significant oldpeak
    p["sig_oldpeak"] = int(
        p["oldpeak"] > 2.0
    )

    # Age group encoding
    p["age_group_middle"] = 0
    p["age_group_senior"] = 0
    p["age_group_elderly"] = 0

    if 40 <= p["age"] < 55:
        p["age_group_middle"] = 1

    elif 55 <= p["age"] < 70:
        p["age_group_senior"] = 1

    elif p["age"] >= 70:
        p["age_group_elderly"] = 1

    processed_patients.append(p)

results = predictor.batch_predict(
    processed_patients
)

for i, result in enumerate(results, start=1):

    print(f"\nPatient {i}")

    print("Label:", result["label"])

    print("Probability:", result["probability"])

    print("Risk Level:", result["risk_level"])

# Save predictions
with open("predictions_log.json", "w") as f:

    json.dump(results, f, indent=2)

print("Saved: predictions_log.json")

# Invalid patient
bad_patient = {
    "age": 15
}

# Test validation
result = predictor.predict(bad_patient)

print(result)

"""
========================================================
HEART DISEASE CLASSIFICATION PROJECT
========================================================

1. PROBLEM STATEMENT
--------------------------------------------------------

The goal of this project was to predict whether a patient
has heart disease using clinical and medical measurements.
This is an important healthcare problem because early
detection of heart disease can help doctors intervene
before severe complications occur.

The model aims to support medical decision-making by
estimating disease probability from patient data.
Reducing false negatives is especially important because
missing a real disease case may delay treatment and
increase patient risk.

This project focuses on building a reliable binary
classification model that balances predictive performance,
generalization, and interpretability.


2. DATASET
--------------------------------------------------------

The dataset used was the Heart Disease dataset containing
patient medical records and diagnostic measurements.
It includes demographic information, ECG measurements,
cholesterol levels, exercise-related metrics, and more.

The dataset contains several hundred patient samples and
multiple clinical features such as age, chest pain type,
blood pressure, cholesterol, maximum heart rate, and ST
depression measurements.

The target variable is:
target = 1 → heart disease present
target = 0 → no heart disease


3. APPROACH
--------------------------------------------------------

The project followed a complete machine learning workflow.
First, exploratory data analysis (EDA) was performed using
histograms, box plots, scatter plots, heatmaps, and class
distribution charts to understand the data structure.

The dataset was then cleaned by handling missing values,
checking outliers using the IQR method, and capping
extreme values where appropriate. Feature engineering was
performed to create medically meaningful variables such
as high cholesterol flags, blood pressure indicators,
heart-rate ratios, and age groups.

Several machine learning models were trained and compared
using cross-validation. The best model was then tuned
using RandomizedSearchCV with ROC-AUC as the optimization
metric before final evaluation.


4. MODELS EVALUATED
--------------------------------------------------------

The following models were evaluated using cross-validation:

- Logistic Regression
- Decision Tree
- Random Forest
- Gradient Boosting
- K-Nearest Neighbors (KNN)

Baseline performance was compared using:
- Cross-validation F1 score
- ROC-AUC
- Accuracy
- Standard deviation across folds

Logistic Regression achieved the strongest overall balance
between performance and generalization. Tree-based models
performed strongly but showed greater overfitting.


5. BEST MODEL
--------------------------------------------------------

The final selected model was Logistic Regression.
It achieved the best combination of validation performance,
stability, interpretability, and generalization on unseen
test data.

Hyperparameter tuning was performed using
RandomizedSearchCV with ROC-AUC scoring. The final model
used tuned values for regularization strength (C),
solver selection, and balanced class weighting.

Logistic Regression was preferred over Random Forest
because it produced a smaller train-test AUC gap and
reduced overfitting while maintaining strong predictive
performance.


6. RESULTS
--------------------------------------------------------

The final tuned Logistic Regression model achieved strong
classification performance on the test dataset.

Key evaluation metrics included:
- Accuracy
- F1 Score
- ROC-AUC
- Sensitivity (Recall)
- Specificity

The model achieved a ROC-AUC above 0.85, indicating good
separation between patients with and without heart disease.
Sensitivity was prioritized because missing real disease
cases is more dangerous than generating false positives.


7. KEY FINDINGS
--------------------------------------------------------

EDA and correlation analysis revealed that chest pain type
(cp), maximum heart rate (thalach), and oldpeak were among
the strongest predictors of heart disease.

Patients with higher chest pain severity and abnormal ST
depression patterns were significantly more likely to show
heart disease. Lower maximum heart rate during exercise
was also associated with higher disease probability.

Feature engineering improved the dataset by introducing
medically meaningful variables such as heart-rate ratio,
blood pressure flags, and cholesterol indicators.


8. LIMITATIONS
--------------------------------------------------------

The dataset is relatively small, which increases the risk
of overfitting and limits the ability of complex models to
generalize perfectly to unseen patients.

The model has not been clinically validated and should not
be used for real medical diagnosis without extensive
testing, calibration, and expert review. Machine learning
predictions should only support medical professionals, not
replace them.

The project also assumes that the training dataset is
representative of real-world patient populations, which
may not always be true across hospitals or demographics.


9. FILES
--------------------------------------------------------

The project generated several output files including:

- heart_model.pkl
- heart_model_metadata.json
- heart_features.json
- heart_final.csv
- predictions_log.json

Charts and evaluation outputs included:
- chart_confusion_final.png
- chart_roc_final.png
- chart_pr_curve.png
- chart_model_comparison.png
- eda_overview.png

These files contain the trained model, metadata,
evaluation results, engineered dataset, feature lists,
and saved prediction logs for deployment and review.

========================================================
END OF PROJECT
========================================================
"""